name: Build release

on: 
  push:
    branches:
      - master


jobs:

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  build:
    runs-on: windows-latest
    needs: tag
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    # Build, test & publish
    - name: Create github release
      run: .\build.ps1 Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
